#!/usr/bin/env bash
# Displays listening TCP/UDP and UNIX domain sockets with associated PID and program name

echo "Active Internet connections (only servers)"
ss -tulnp | grep LISTEN

echo
echo "Active UNIX domain sockets (only servers)"
ss -xlnp | grep LISTEN
