#!/usr/bin/env bash
# Script that listen to port 98 on localhost

# Verify that the script is run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root (use sudo)" >&2
    exit 1
fi

# Listen to port 98 on localhost
echo "Starting listening on port 98..."
nc -l 98
